<!-- event.phtml -->
<?php
$prefixes = '
PREFIX cphm: <' . $this->namespaces["cphm"] . '>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> ';

$classTypeof = $prefixes . 'SELECT *
WHERE {
	<'.$this->resourceUri.'> rdf:type ?resourceClass . 
	?resourceClass rdfs:label ?resourceUri .
	FILTER (lang(?resourceUri) = "de")
}';
$classTypeof = $this->querylist( $classTypeof, 'local/items/plain.phtml');
?>

<div class="page-header">
	<h2 class=""><?php echo $this->title ?> <small>(<?php echo $classTypeof; ?>)</small></h2>
</div>

<?php
$person = $this->query(array('where' => '?resourceUri <' . $this->namespaces["cphm"] . 'hasPeriod> <'.$this->resourceUri.'>', 'template' => 'resource'));
if ( $person != "" ) {
	echo "<h3>Von</h3>";
	echo $person;
}

/*
Weitere Infos
*/
$furtherProperties = array(
	"Ort" => "periodPlace",
	"Körperschaft" => "periodBody",
	"von" => "from",	
	"bis" => "to",
	"Datum" => "date",
	"Anmerkung" => "note",
);

foreach ($furtherProperties as $key => $value) {
	$property = $this->query(array('where' => '<' . $this->resourceUri . '> <' . $this->namespaces["cphm"] . $value.'> ?resourceUri', 'template' => 'liplain'));
	if ( $property != "" ) {
		echo "<h3>".$key."</h3>";
		echo $property;
	}
} 

?>